# Version catalog is a central place for you to declare and version dependencies
# https://docs.gradle.org/current/userguide/platforms.html#sub:version-catalog
# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

[versions]
ksp = "2.3.4"
fory = "0.14.1"
hubbo = "0.0.1"
jooq = "3.20.10"
kotlin = "2.3.0"
moshi = "1.15.2"
javaSource = "25"
javaTarget = "25"
rxJava = "3.1.12"
javapoet = "1.3.0"
mapstruct = "1.6.3"
springBoot = "4.0.1"
guava = "33.5.0-jre"
commonsIo = "2.20.0"
fastjson2 = "2.0.60"
postgresql = "42.7.8"
kotlinSpring = "2.3.0"
commonsPool2 = "2.13.1"
commonsCodec = "1.19.0"
commonsLang3 = "3.19.0"
springCloud = "2025.1.0"
reactiveStreams = "1.0.4"
reactiveVersion = "3.8.2"
googleAutoService = "1.1.1"
kotlinxCoroutines = "1.10.2"
commonsCollections4 = "4.5.0"
postgresqlR2dbc = "1.1.1.RELEASE"
springDependencyManagement = "1.1.7"
transmittableThreadLocal = "2.14.5"
jspecify = "1.0.0"
sl4j = "2.0.17"
log4jTemplateJson = "2.25.3"
lombok = "1.18.42"
kotlinReactorExtension = "1.3.0"
disruptor = "4.0.0"
r2dbcPool = "1.0.2.RELEASE"
kspSymbol = "2.3.4"
kotlinPoet = "2.2.0"
kotlinxMetadata = "0.9.0"

[libraries]
guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }
moshi = { group = "com.squareup.moshi", name = "moshi", version.ref = "moshi" }
fory-core = { group = "org.apache.fory", name = "fory-core", version.ref = "fory" }
commons-io = { group = "commons-io", name = "commons-io", version.ref = "commonsIo" }
rx-java = { group = "io.reactivex.rxjava3", name = "rxjava", version.ref = "rxJava" }
mapstruct = { group = "org.mapstruct", name = "mapstruct", version.ref = "mapstruct" }
fory-kotlin = { group = "org.apache.fory", name = "fory-kotlin", version.ref = "fory" }
fastjson2 = { group = "com.alibaba.fastjson2", name = "fastjson2", version.ref = "fastjson2" }
commons-codec = { group = "commons-codec", name = "commons-codec", version.ref = "commonsCodec" }
moshi-adapters = { group = "com.squareup.moshi", name = "moshi-adapters", version.ref = "moshi" }
postgresql-driver = { group = "org.postgresql", name = "postgresql", version.ref = "postgresql" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
spring-boot-starter-test = { group = "org.springframework.boot", name = "spring-boot-starter-test" }
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin" }
reactor-core = { group = "io.projectreactor", name = "reactor-core", version.ref = "reactiveVersion" }
commons-lang3 = { group = "org.apache.commons", name = "commons-lang3", version.ref = "commonsLang3" }
commons-pool2 = { group = "org.apache.commons", name = "commons-pool2", version.ref = "commonsPool2" }
postgresql-r2dbc = { group = "org.postgresql", name = "r2dbc-postgresql", version.ref = "postgresqlR2dbc" }
spring-boot-starter-web-flux = { group = "org.springframework.boot", name = "spring-boot-starter-webflux" }
moshi-kotlin-codegen = { group = "com.squareup.moshi", name = "moshi-kotlin-codegen", version.ref = "moshi" }
reactive-streams = { group = "org.reactivestreams", name = "reactive-streams", version.ref = "reactiveStreams" }
commons-collections4 = { group = "org.apache.commons", name = "commons-collections4", version.ref = "commonsCollections4" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
transmittable-thread-local = { group = "com.alibaba", name = "transmittable-thread-local", version.ref = "transmittableThreadLocal" }
kotlinx-coroutines-reactor = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-reactor", version.ref = "kotlinxCoroutines" }
java-poet = { group = "com.squareup", name = "javapoet", version.ref = "javapoet" }
google-auto-service = { group = "com.google.auto.service", name = "auto-service", version.ref = "googleAutoService" }
jspecify = { group = "org.jspecify", name = "jspecify", version.ref = "jspecify" }
sl4j = { group = "org.slf4j", name = "slf4j-api", version.ref = "sl4j" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
spring-dependency-management-plugin = { group = "io.spring.gradle", name = "dependency-management-plugin", version.ref = "springDependencyManagement" }
spring-boot-plugin = { group = "org.springframework.boot", name = "org.springframework.boot.gradle.plugin", version.ref = "springBoot" }
kotlin-allopen = { group = "org.jetbrains.kotlin", name = "kotlin-allopen", version.ref = "kotlin" }
kotlin-noarg = { group = "org.jetbrains.kotlin", name = "kotlin-noarg", version.ref = "kotlin" }
kotlin-spring-plugin = { group = "org.jetbrains.kotlin.plugin.spring", name = "org.jetbrains.kotlin.plugin.spring.gradle.plugin", version.ref = "kotlin" }
kotlin-jvm-plugin = { group = "org.jetbrains.kotlin.jvm", name = "org.jetbrains.kotlin.jvm.gradle.plugin", version.ref = "kotlin" }
spring-boot-dependencies = { group = "org.springframework.boot", name = "spring-boot-dependencies", version.ref = "springBoot" }
log4j-json-layout = { group = "org.apache.logging.log4j", name = "log4j-layout-template-json", version.ref = "log4jTemplateJson" }
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
jooq-meta-kotlin = { group = "org.jooq", name = "jooq-meta-kotlin", version.ref = "jooq" }
reactor-kotlin-extensions = { group = "io.projectreactor.kotlin", name = "reactor-kotlin-extensions", version.ref = "kotlinReactorExtension" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
disruptor = { group = "com.lmax", name = "disruptor", version.ref = "disruptor" }
r2dbc-pool = { group = "io.r2dbc", name = "r2dbc-pool", version.ref = "r2dbcPool" }
moshi-kotlin = { group = "com.squareup.moshi", name = "moshi-kotlin", version.ref = "moshi" }
ksp = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
# KSP API
ksp-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "kspSymbol" }
# KSP 处理器的运行时支持
ksp-processor = { module = "com.google.devtools.ksp:symbol-processing", version.ref = "kspSymbol" }
# 用于生成代码的 KotlinPoet
kotlinpoet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinPoet" }
kotlinpoet-ksp = { module = "com.squareup:kotlinpoet-ksp", version.ref = "kotlinPoet" }
# Kotlin 元数据
kotlinx-metadata = { module = "org.jetbrains.kotlinx:kotlinx-metadata-jvm", version.ref = "kotlinxMetadata" }
kotlin-kapt = { group = "org.jetbrains.kotlin.kapt", name = "org.jetbrains.kotlin.kapt.gradle.plugin", version.ref = "kotlin" }
fastjson2-extension = { group = "com.alibaba.fastjson2", name = "fastjson2-extension", version.ref = "fastjson2" }
fastjson2-kotlin = { group = "com.alibaba.fastjson2", name = "fastjson2-kotlin", version.ref = "fastjson2" }


[bundles]
r2dbc = ["postgresql-r2dbc", "r2dbc-pool"]
alibaba = ["fastjson2", "fastjson2-kotlin"]
squareup = ["java-poet"]
annotations = ["jspecify"]
alipay = ["fory-core", "fory-kotlin"]
google = ["guava", "google-auto-service"]
kotlin = ["kotlin-stdlib", "kotlin-reflect", "kotlinx-metadata"]
reactive = ["rx-java", "reactor-core", "reactive-streams"]
moshi = ["moshi", "moshi-adapters", "moshi-kotlin-codegen"]
coroutines = ["kotlinx-coroutines-core", "kotlinx-coroutines-reactor"]
apache = ["commons-io", "commons-lang3", "commons-codec", "commons-collections4", "commons-pool2"]
logging = ["sl4j", "log4j-json-layout"]
ksp-processor = ["ksp", "ksp-processor", "kotlinpoet", "kotlinpoet-ksp"]

[plugins]
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
jooq-codegen = { id = "org.jooq.jooq-codegen-gradle", version.ref = "jooq" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlinSpring" }
kotlinGradlePlugin = { id = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "springDependencyManagement" }
